"""Added vendors table

Revision ID: 2d5dd9127afe
Revises: 8a4f8bd785d2
Create Date: 2025-01-06 23:22:23.153232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d5dd9127afe'
down_revision: Union[str, None] = '8a4f8bd785d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
