"""Corrected name

Revision ID: 512ad1090b48
Revises: e63c3eca765d
Create Date: 2025-01-07 00:34:19.407579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '512ad1090b48'
down_revision: Union[str, None] = 'e63c3eca765d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('portfolio', sa.String(length=225), nullable=False))
    op.drop_column('vendors', 'Portfolio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('Portfolio', mysql.VARCHAR(length=225), nullable=False))
    op.drop_column('vendors', 'portfolio')
    # ### end Alembic commands ###
