"""Added performance column

Revision ID: 8a4f8bd785d2
Revises: 
Create Date: 2025-01-06 19:09:52.701456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8a4f8bd785d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('performance', sa.Integer(), nullable=True))
    op.alter_column('users', 'state',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=225),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'state',
               existing_type=sa.String(length=225),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_column('users', 'performance')
    # ### end Alembic commands ###
