"""Replace first_name & last_name to name

Revision ID: e63c3eca765d
Revises: fb4e6ca7b481
Create Date: 2025-01-07 00:27:45.491679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e63c3eca765d'
down_revision: Union[str, None] = 'fb4e6ca7b481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('name', sa.String(length=225), nullable=False))
    op.drop_column('vendors', 'first_name')
    op.drop_column('vendors', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('last_name', mysql.VARCHAR(length=225), nullable=False))
    op.add_column('vendors', sa.Column('first_name', mysql.VARCHAR(length=225), nullable=False))
    op.drop_column('vendors', 'name')
    # ### end Alembic commands ###
