"""Added new column to vendors table

Revision ID: fb4e6ca7b481
Revises: 2d5dd9127afe
Create Date: 2025-01-06 23:41:50.340352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb4e6ca7b481'
down_revision: Union[str, None] = '2d5dd9127afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('first_name', sa.String(length=225), nullable=False))
    op.add_column('vendors', sa.Column('last_name', sa.String(length=225), nullable=False))
    op.drop_column('vendors', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('name', mysql.VARCHAR(length=225), nullable=False))
    op.drop_column('vendors', 'last_name')
    op.drop_column('vendors', 'first_name')
    # ### end Alembic commands ###
